[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='1c5a3a2fd190feb8a27b393535f522ca18f847efa302615fbcc1c011c4f21856'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
